### ISSUE TITLE
Windows 10 Has a Taskbar Window You Can't Get Rid of

### ISSUE THREAD

**Issue by dsnvwlmnt** [JusKillmeQik/LevelingGuide#25]
Didn't exist in the previous version. "Gui Exp". Closing it doesn't work, can't really interact with it.

![image](https://user-images.githubusercontent.com/14173022/64495416-9fb17500-d24e-11e9-9673-814ae7d60966.png)

**Comment by JusKillmeQik** [comment]
I don't see this, so it will be hard for me to fix. Is it causing any problems that you can describe?

**Comment by dsnvwlmnt** [comment]
Nope it's benign.
