### ISSUE TITLE
Add Option to Hide EXP

### ISSUE THREAD

**Issue by dsnvwlmnt** [JusKillmeQik/LevelingGuide#27]

**Comment by JusKillmeQik** [comment]
This option already exists with Alt+F3

**Comment by dsnvwlmnt** [comment]
Sorry I meant hide it by default. You asked me to post an issue to remind you, I didn't make the title descriptive enough.

**Comment by JusKillmeQik** [comment]
It now starts hidden if you set startHidden to 1 in the config.

**Comment by dsnvwlmnt** [comment]
Hmm but the EXP comes right back, as soon as you toggle on the other stuff. It toggles on and off with the other things from then on.

As a hack fix for now I've set _"levelXoffset" : "1"_, as you suggested to someone else in the reddit thread.
