### ISSUE TITLE
Problem with maxGuideWidth

### ISSUE THREAD

**Issue by Exicucumber** [JusKillmeQik/LevelingGuide#29]
I have attached two screenshots that display the problem. One is with standard maxGuideWidth set to 50, the other one is maxGuideWidth set to 80.
The last text is missing (more precisely hidden), and the entirety of the guide section isn't used. This could just be an issue with my setup, let me know if you can't reproduce it.

![Standard](https://user-images.githubusercontent.com/749256/69975993-915eb680-1528-11ea-8aa2-6882b9f73f90.png)
![Wide](https://user-images.githubusercontent.com/749256/69975995-91f74d00-1528-11ea-91f4-078006a13068.png)

**Comment by Exicucumber** [comment]
I can see that if you use the same value for both "maxNotesWidth" and "maxGuideWidth", then there is no cutoff issue.
So the issue only seems to be apparent when you want to use a different width for one of them.

**Comment by JusKillmeQik** [comment]
Thanks for finding and debugging the problem! It's fixed in the patch that will go out tonight.

**Comment by JusKillmeQik** [comment]
Fixed in 928bceecc639e397700e078cfe2a64da24740cc1
