### ISSUE TITLE
"Call to nonexistent function" when starting the latest version from master branch

### ISSUE THREAD

**Issue by josemaia** [JusKillmeQik/LevelingGuide#31]
---------------------------
LevelingGuide.ahk
---------------------------
Error:  Call to nonexistent function.

Specifically: Max( Abs(CurrentLevel - monsterLevel) - safeZone, 0 )

	Line#
	765: monsterLevel = 77.54
	766: }
	766: Else
	766: if (monsterLevel = 84)  
	766: {
	767: monsterLevel = 77.70
	768: }
--->	770: effectiveDiff := Max( Abs(CurrentLevel - monsterLevel) - safeZone, 0 )
	771: expPenalty := (CurrentLevel+5)/(CurrentLevel+5+Sqrt(effectiveDiff*effectiveDiff*effectiveDiff*effectiveDiff*effectiveDiff))
	772: expMulti := Sqrt(expPenalty*expPenalty*expPenalty)
	773: if (CurrentLevel >= 95)  
	773: {
	774: expMulti := expMulti * (1/(1+(0.1*(CurrentLevel-94))))
	775: }
	777: expMulti := Max( expMulti, 0.01 )

The program will exit.
---------------------------
OK   
---------------------------

**Comment by josemaia** [comment]
Fixed when updating from 1.1.26.01 to 1.1.32.00.

**Comment by JusKillmeQik** [comment]
Fixed in 2d337e40729746d4e827942192bd8fb892b0124e
